# Generated by Django 5.2.8 on 2025-11-06 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClubMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('discord', models.CharField(blank=True, max_length=100)),
                ('school', models.CharField(max_length=200)),
                ('year', models.CharField(choices=[('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Fourth Year'), ('5', 'Fifth Year')], max_length=1)),
                ('department_choice_1', models.CharField(choices=[('cybersec', 'Cybersecurity'), ('dev', 'Development'), ('eth', 'Ethical hacking'), ('ai', 'Artificial Intelligence'), ('design', 'Design and Social media'), ('hr', 'Human Recourses'), ('fpr', 'finance and public relations'), ('logistics', 'Logistics'), ('vib', 'Vibes')], max_length=20)),
                ('department_choice_2', models.CharField(choices=[('cybersec', 'Cybersecurity'), ('dev', 'Development'), ('eth', 'Ethical hacking'), ('ai', 'Artificial Intelligence'), ('design', 'Design and Social media'), ('hr', 'Human Recourses'), ('fpr', 'finance and public relations'), ('logistics', 'Logistics'), ('vib', 'Vibes')], max_length=20)),
                ('why_department_1', models.TextField(help_text='Why did you choose your first department?')),
                ('why_not_department_1_choose_2', models.TextField(blank=True, help_text='If not accepted to department 1, why department 2?')),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
    ]
