# Generated by Django 5.2.8 on 2025-12-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clubmember',
            name='department_choice_1',
            field=models.CharField(choices=[('cybersec', 'Cybersecurity'), ('dev', 'Development'), ('eth', 'Ethical hacking'), ('ai', 'Artificial Intelligence'), ('design', 'Design and Social media'), ('hr', 'Human Recourses'), ('fpr', 'Finance and public relations'), ('logistics', 'Logistics'), ('vib', 'Vibes')], max_length=20),
        ),
        migrations.AlterField(
            model_name='clubmember',
            name='department_choice_2',
            field=models.CharField(choices=[('cybersec', 'Cybersecurity'), ('dev', 'Development'), ('eth', 'Ethical hacking'), ('ai', 'Artificial Intelligence'), ('design', 'Design and Social media'), ('hr', 'Human Recourses'), ('fpr', 'Finance and public relations'), ('logistics', 'Logistics'), ('vib', 'Vibes')], max_length=20),
        ),
    ]
