# Generated by Django 5.2.8 on 2025-12-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club_registration', '0002_alter_clubmember_department_choice_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clubmember',
            name='department_choice_3',
            field=models.CharField(choices=[('cybersec', 'Cybersecurity'), ('dev', 'Development'), ('eth', 'Ethical hacking'), ('ai', 'Artificial Intelligence'), ('design', 'Design and Social media'), ('logistics', 'Logistics'), ('vib', 'Vibes')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='clubmember',
            name='why_not_department_1_and_2_choose_3',
            field=models.TextField(blank=True, help_text='If not accepted to neither in department 1 nor 2, why department 3?', null=True),
        ),
        migrations.AlterField(
            model_name='clubmember',
            name='department_choice_1',
            field=models.CharField(choices=[('cybersec', 'Cybersecurity'), ('dev', 'Development'), ('eth', 'Ethical hacking'), ('ai', 'Artificial Intelligence'), ('design', 'Design and Social media'), ('logistics', 'Logistics'), ('vib', 'Vibes')], max_length=20),
        ),
        migrations.AlterField(
            model_name='clubmember',
            name='department_choice_2',
            field=models.CharField(choices=[('cybersec', 'Cybersecurity'), ('dev', 'Development'), ('eth', 'Ethical hacking'), ('ai', 'Artificial Intelligence'), ('design', 'Design and Social media'), ('logistics', 'Logistics'), ('vib', 'Vibes')], max_length=20),
        ),
    ]
