# Generated by Django 5.2.8 on 2025-12-03 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stands', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_hash', models.CharField(help_text='Hashed flag code', max_length=128, unique=True)),
                ('base_points', models.IntegerField(choices=[(100, '100'), (200, '200'), (300, '300'), (400, '400'), (500, '500')])),
                ('is_used', models.BooleanField(default=False, help_text='Has this flag been claimed?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='stands.stand')),
            ],
            options={
                'ordering': ['stand', 'base_points'],
            },
        ),
        migrations.CreateModel(
            name='FlagSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('awarded_points', models.IntegerField(help_text='Points (same as flag base_points)')),
                ('flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='game.flag')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flag_submissions', to='teams.team')),
            ],
            options={
                'ordering': ['-submitted_at'],
                'unique_together': {('team', 'flag')},
            },
        ),
    ]
