# Generated by Django 5.2.8 on 2025-12-05 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPhase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_phase', models.CharField(choices=[('GAME_ACTIVE', 'Game Active (Teams Can Play)'), ('POST_EVENT', 'Post-Event (Club Registration Only)')], default='GAME_ACTIVE', help_text='Current event phase', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Event Phase',
                'verbose_name_plural': 'Event Phase',
            },
        ),
    ]
