# Generated by Django 5.2.8 on 2025-11-06 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stands', '0001_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamGemCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collected_at', models.DateTimeField(auto_now_add=True)),
                ('flag_used', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_collection', to='stands.flag')),
                ('gem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collected_by_teams', to='stands.gem')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collected_gems', to='teams.team')),
            ],
            options={
                'ordering': ['-collected_at'],
                'unique_together': {('team', 'gem')},
            },
        ),
    ]
