# Generated by Django 5.2.8 on 2025-11-06 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gem_type', models.CharField(choices=[('blue', 'Blue Gem'), ('pink', 'Pink Gem'), ('green', 'Green Gem'), ('yellow', 'Yellow Gem'), ('red', 'Red Gem')], max_length=20, unique=True)),
                ('kingdom', models.CharField(choices=[('candy', 'Candy Kingdom'), ('ice', 'Ice Kingdom'), ('lumpy', 'Lumpy Space'), ('fire', 'Fire Kingdom'), ('grass', 'Grasslands')], max_length=50)),
                ('description', models.TextField()),
                ('points', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['kingdom', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Flag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_code_hash', models.CharField(max_length=64, unique=True)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_flags', to=settings.AUTH_USER_MODEL)),
                ('gem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physical_flags', to='stands.gem')),
            ],
            options={
                'ordering': ['gem', 'created_at'],
            },
        ),
    ]
