# Generated by Django 5.2.8 on 2025-12-02 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='the name of the stand', max_length=100, unique=True)),
                ('game_type', models.CharField(help_text="Type of game/challenge (e.g., 'Arduino', 'Memory flip', 'Hacking room')", max_length=100)),
                ('duration_minutes', models.IntegerField(default=15, help_text='Recommended time for this challenge (minutes)')),
                ('description', models.TextField(blank=True, help_text='Detailed description of the challenge')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Stand',
                'verbose_name_plural': 'Stands',
                'ordering': ['name'],
            },
        ),
    ]
