# Generated by Django 5.2.8 on 2025-12-03 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stands', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stand',
            name='description',
        ),
    ]
